### Questão 1
Dadas as seguintes matrizes, calcule as medidas de avaliação baseadas na matriz de confusão (TFP, TFN, TVN, TVP).

Matriz de confusão do classificador '1' <br>
[[41 59]  <br>
 [ 3 97]] <br>
Matriz de confusão do classificador '2' <br>
[[96  4]  <br>
 [ 5 95]]  <br>
Matriz de confusão do classificador '3'   <br>
[[98  2]  <br>
 [ 3 97]]  <br>
e escolha a **alternativa correta**. <br>

a)	A precisão obtida pelo Classificador '1' foi maior que para o Classificador '2'.<br>
b)	As acurácias obtidas pelos três classificadores foram acima de 0.90 . <br>
c)	Pode-se dizer que o Classificador '3' foi melhor que os demais, pois apresentou maior valor em todas as métricas calculadas.  <br>
d)	O valor do F1-score foi maior para Classificador '1' do que para a Classificador '3'. <br>
e)	Nenhuma das anteriores. <br>

In [4]:
# Código executado para mostrar as métricas (TFP, TFN, TVN, TVP, Precisão, Acurácia, F1)
import numpy as np
import pandas as pd
from math import isclose

# Matrizes fornecidas (formato: [[TN, FP], [FN, TP]])
cms = {
    '1': np.array([[41, 59],
                   [ 3, 97]]),
    '2': np.array([[96, 4],
                   [ 5, 95]]),
    '3': np.array([[98, 2],
                   [ 3, 97]])
}

rows = []
for key, cm in cms.items():
    TN, FP = int(cm[0,0]), int(cm[0,1])
    FN, TP = int(cm[1,0]), int(cm[1,1])
    total = TN + FP + FN + TP
    
    # métricas (TFP = taxa de falso positivo (FP/(FP+TN)); TFN = taxa de falso negativo (FN/(FN+TP))
    TFP = FP / (FP + TN)
    TFN = FN / (FN + TP)
    TVN = TN / (TN + FP)   # taxa verdadeira negativo / especificidade
    TVP = TP / (TP + FN)   # taxa verdadeira positivo / recall
    Precision = TP / (TP + FP) if (TP + FP) > 0 else 0
    Accuracy = (TP + TN) / total
    Recall = TVP
    F1 = 2 * Precision * Recall / (Precision + Recall) if (Precision + Recall) > 0 else 0
    
    rows.append({
        'Classifier': key,
        'TN': TN, 'FP': FP, 'FN': FN, 'TP': TP, 'Total': total,
        'TFP': TFP, 'TFN': TFN, 'TVN': TVN, 'TVP': TVP,
        'Precision': Precision, 'Accuracy': Accuracy, 'F1': F1,
        'TFP_frac': f"{FP}/{FP+TN}",
        'TFN_frac': f"{FN}/{FN+TP}",
        'TVN_frac': f"{TN}/{TN+FP}",
        'TVP_frac': f"{TP}/{TP+FN}",
        'Precision_frac': f"{TP}/{TP+FP}",
        'Accuracy_frac': f"{TP+TN}/{total}"
    })

df = pd.DataFrame(rows).set_index('Classifier')

# Mostrar tabela com três casas decimais nas métricas principais
display_df = df[['TN','FP','FN','TP','Total',
                 'TFP','TFN','TVN','TVP',
                 'Precision','Accuracy','F1']].copy()
display_df = display_df.round({
    'TFP':3,'TFN':3,'TVN':3,'TVP':3,'Precision':3,'Accuracy':3,'F1':3
})

# Apresenta a tabela
try:
    # exibe como tabela interativa caso a função esteja disponível
    import caas_jupyter_tools as cjt
    cjt.display_dataframe_to_user("Métricas por classificador", display_df)
except Exception:
    print(display_df)

# Verificação das alternativas pedidas
prec1 = df.loc['1','Precision']
prec2 = df.loc['2','Precision']
prec3 = df.loc['3','Precision']

acc1 = df.loc['1','Accuracy']
acc2 = df.loc['2','Accuracy']
acc3 = df.loc['3','Accuracy']

f1_1 = df.loc['1','F1']
f1_2 = df.loc['2','F1']
f1_3 = df.loc['3','F1']

# (a) Precisão 1 > Precisão 2 ?
opt_a = prec1 > prec2

# (b) acurácias dos três > 0.90 ?
opt_b = (acc1 > 0.90) and (acc2 > 0.90) and (acc3 > 0.90)

# (c) Classificador 3 tem MAIOR valor em TODAS as métricas calculadas?
# interpretamos "maior valor" como estritamente maior numericamente para cada métrica
metrics = ['TFP','TFN','TVN','TVP','Precision','Accuracy','F1']
opt_c = all(df.loc['3',m] > df.loc['1',m] and df.loc['3',m] > df.loc['2',m] for m in metrics)

# (d) F1 do 1 > F1 do 3 ?
opt_d = f1_1 > f1_3

# Resultado final
print("\nComparações (True = alternativa VERDADEIRA):")
print(f"(a) Precisão(1) > Precisão(2)? --> {opt_a}   (prec1={prec1:.6f}, prec2={prec2:.6f})")
print(f"(b) Todas acurácias > 0.90? --> {opt_b}   (acc1={acc1:.6f}, acc2={acc2:.6f}, acc3={acc3:.6f})")
print(f"(c) Classif.3 tem MAIOR valor em TODAS métricas? --> {opt_c}")
print(f"    (valores resumidos: Classif3 vs Classif1 vs Classif2)")
for m in metrics:
    print(f"    {m}: {df.loc['3',m]:.6f} vs {df.loc['1',m]:.6f} vs {df.loc['2',m]:.6f}")
print(f"(d) F1(1) > F1(3)? --> {opt_d}   (F1_1={f1_1:.6f}, F1_3={f1_3:.6f})")

# Conclusão lógica
if not (opt_a or opt_b or opt_c or opt_d):
    conclusion = "Alternativa correta: (e) Nenhuma das anteriores."
else:
    true_opts = []
    if opt_a: true_opts.append('(a)')
    if opt_b: true_opts.append('(b)')
    if opt_c: true_opts.append('(c)')
    if opt_d: true_opts.append('(d)')
    conclusion = "Alternativa(s) verdadeira(s): " + ", ".join(true_opts)

print("\n" + conclusion)


            TN  FP  FN  TP  Total   TFP   TFN   TVN   TVP  Precision  \
Classifier                                                             
1           41  59   3  97    200  0.59  0.03  0.41  0.97      0.622   
2           96   4   5  95    200  0.04  0.05  0.96  0.95      0.960   
3           98   2   3  97    200  0.02  0.03  0.98  0.97      0.980   

            Accuracy     F1  
Classifier                   
1              0.690  0.758  
2              0.955  0.955  
3              0.975  0.975  

Comparações (True = alternativa VERDADEIRA):
(a) Precisão(1) > Precisão(2)? --> False   (prec1=0.621795, prec2=0.959596)
(b) Todas acurácias > 0.90? --> False   (acc1=0.690000, acc2=0.955000, acc3=0.975000)
(c) Classif.3 tem MAIOR valor em TODAS métricas? --> False
    (valores resumidos: Classif3 vs Classif1 vs Classif2)
    TFP: 0.020000 vs 0.590000 vs 0.040000
    TFN: 0.030000 vs 0.030000 vs 0.050000
    TVN: 0.980000 vs 0.410000 vs 0.960000
    TVP: 0.970000 vs 0.970000 vs 0.950

### Questão 02.

Suponha que em um problema de classificação binária de um dataset balanceado, um ciêntista de dados treinou três modelos diferentes e obteve as seguintes acurácias em um determinado conjunto de treino/teste:

1. **Modelo A:** Treino = 0.95, Teste = 0.38
2. **Modelo B:** Treino = 0.75, Teste = 0.74
3. **Modelo C:** Treino = 0.35, Teste = 0.75

O que **NÃO** podemos afirmar sobre esses modelos?

a) O Modelo A apresentou overfit, pois apesar de obter uma acurácia alta no conjunto de treino, não conseguiu generalizar e obteve baixo desempenho no conjunto de teste. <br>
b) O Modelo B apresentou melhor grau de generalização entre os modelos testados. <br>
c) O Modelo C provavelmente irá apresentar melhor desempenho quando colocado em produção, visto que seu desempenho no conjunto de teste é melhor. <br>
d) O Modelo C, apesar de apresentar o melhor desempenho no conjunto de teste, apresentou uma diferença considerável de desempenho entre os conjuntos de treino e teste, indicando baixo grau de conhecimento. Dessa forma, seu desempenho quando colocado em produção muito provavelmente não será tão bom quanto o do Modelo B.<br>


### Questão 3

Em relação as métricas de avaliação utilizadas para avaliação do desempenho de algoritmos de Aprendizado de Máquina, o que não podemos afirmar:<br>
a) As métricas mse, mae e R2 são indicadas para problemas de regressão. <br>
b) As métricas precisão e revocação são usadas para geração da curva ROC, sendo que no eixo x coloca-se a revocação e no eixo y a precisão. <br>
c) A métrica F1-score faz uma ponderação entre precisão e revocação.<br>
d) As curvas ROC ajudam na escolha do algoritmo mais adequado, pois, quanto mais próximo do canto superior esquerdo a curva de desempenho estiver melhor é o algoritmo.<br>
e) nenhuma das anteriores.


### Questão 4

Escolha a alternativa CORRETA sobre o Naive Bayes:

a) Assume que todos os atributos são independentes entre si.

b) Não pode ser usado para classificação multiclasse, apenas para problemas de classificação binária.

c) Consegue lidar apenas com atributos categóricos, sendo de uso limitado para atributos contínuos.

d) É robusto a outliers e valores ausentes, pois não afetam a probabilidade condicional.

e) Possui muitos hiperparâmetros que precisam ser calibrados e estimados para seu funcionamento correto.

### Questão 5

Escolha a alternativa INCORRETA sobre o Árvores de Decisão:

a) Podem lidar com atributos categóricos e numéricos.

b) São facilmente interpretáveis e permitem a visualização do processo de tomada de decisão.

c) Sempre aprendem modelos resistentes ao overfitting.

d) Permitem estimar os atributos mais relevantes da base.

e) Podem capturar tanto relações lineares quanto não lineares nos dados